name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.0
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Version
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Publish EventStore.Inspector.Common
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: EventStore.Inspector.Common/EventStore.Inspector.Common.csproj
        PACKAGE_NAME: EventStore.Inspector.Common
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        VERSION_STATIC: ${{steps.gitversion.outputs.nuGetVersion}}
